version: '3'

services:
    backend:
        container_name: backend
        build:
            context: backend
        ports:
            - '3000:3000'
        links:
            - mongodb
        depends_on:
            - mongodb
    frontend:
        container_name: frontend
        build:
            context: frontend
        ports:
            - '8070:80'
        links:
            - backend
        depends_on:
            - backend
        environment:
            - BACKEND_IP=backend
    mongodb:
        container_name: mongodb
        image: mongodb/mongodb-community-server:6.0-ubi8
        # environment:
        #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
        #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        #restart: always
        ports:
            - '27017:27017'
